### ISSUE TITLE
Dual cluster setup

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/plugin-remote-kubernetes#1]
I can envision a scenario in which someone wants to use 2 Kubernetes clusters:

- The first cluster serves as the central hub and control panel for managing multiple environments, specifically hosting **Racetrack services**
- Meanwhile, the other cluster (or clusters) are responsible for running **jobs**. 

This could be the case when some jobs demand more memory than others and you want to move them out to AKS, EKS, or similar. This decision may be driven by pricing.

Nevertheless, it's currently not possible due to the fact that this infrastructure plugin expects kube-api to be located in the same local cluster.

**Comment by iszulcdeepsense** [comment]
@JosefAssadERST  heads-up

**Comment by JosefAssadERST** [comment]
In my mind, the core issue here is this: as seen in the docker daemon ITP, I see the way an ITP works to be:

The ITP gets installed; **it is target-neutral**. So right after installing it, you still can't deploy to a specific infrastructure type, but you can define actual instances of that type and *then* you can deploy to them.

Right now, the way this plugin works is as you said by speaking directly to a local kube api. So this ITP currently is not a good representation of what a well-formed RT ITP should look like.

Seems to me there's a couple of ways to resolve this. Either "neutralise" the current k8s ITP so it can speak to a kube API anywhere, and let the user provide the details, or make the current k8s ITP an "in-situ" version and make a second "anywhere" k8s ITP.
